final class Assets {
  Assets._();

  static const String _icons = 'assets/icons';
  static const String _images = 'assets/images';
  static const String ballyKoke = '$_icons/bally-koke.svg';
  static const String checkCircle = '$_icons/check-circle.svg';
  static const String notification = '$_icons/notification.svg';
  static const String search = '$_icons/search.svg';
  static const String topSticker = '$_icons/top-sticker.svg';
  static const String track = '$_icons/track.svg';
  static const String star = '$_icons/star.svg';
  static const String clock = '$_icons/clock.svg';
  static const String spoonAndFork = '$_icons/spoon-and-fork.svg';
  static const String home = '$_icons/home.svg';
  static const String categories = '$_icons/categories.svg';
  static const String cashbackPrize = '$_icons/cashback-prize.svg';
  static const String shoppingCart = '$_icons/shopping-cart.svg';
  static const String profile = '$_icons/profile.svg';
  static const String heart = '$_icons/heart.svg';
  static const String filter = '$_icons/filter.svg';
  static const String arrowLeft = '$_icons/arrow-left.svg';
  static const String searchWhite = '$_icons/search-white.svg';
  static const String calorie = '$_icons/calorie.svg';
  static const String weight = '$_icons/weight.svg';
  static const String chevronDown = '$_icons/chevron-down.svg';
  static const String call = '$_icons/call.svg';
  static const String instagram = '$_icons/instagram.svg';
  static const String location = '$_icons/location.svg';
  static const String internet = '$_icons/internet.svg';
  static const String user = '$_icons/user.svg';
  static const String pen = '$_icons/pen.svg';
  static const String open = '$_icons/open.svg';
  static const String mapLocation = '$_icons/map-location.svg';
  static const String cubeBox = '$_icons/cube-box.svg';
  static const String language = '$_icons/language.svg';
  static const String message = '$_icons/message.svg';
  static const String checkShield = '$_icons/check-shield.svg';
  static const String chevronRight = '$_icons/chevron-right.svg';
  static const String moon = '$_icons/moon.svg';
  static const String settings = '$_icons/settings.svg';
  static const String sun = '$_icons/sun.svg';
  static const String delete = '$_icons/delete.svg';
  static const String fork = '$_icons/fork.svg';
  static const String comment = '$_icons/comment.svg';
  static const String delivered = '$_icons/delivered.svg';
  static const String pending = '$_icons/pending.svg';
  static const String rejected = '$_icons/rejected.svg';
  static const String deliveredWO = '$_icons/delivered-w-o.svg';
  static const String refresh = '$_icons/refresh.svg';
  static const String messageOutline = '$_icons/message-outline.svg';
  static const String radioOn = '$_icons/radio-on.svg';

  static const String foodGroup = '$_images/food-group.png';
  static const String desertGroup = '$_images/desert-group.png';
  static const String someFoods = '$_images/some-foods.png';
}
